/* eslint-disable */
// This file is generated by scripts/export-website-status.mjs.
// Source of truth: project-context/website-status.json.
// Do not edit manually.

export type ProjectStatus = {
  productName: string;
  statusLabel: string;
  statusDescription: string;
  updatedAt: string;
  availableNow: string[];
  inProgress: string[];
  planned: string[];
  proofPoints: string[];
  limitations: string[];
  featureSections: Array<{
    title: string;
    description: string;
    items: string[];
  }>;
};

export const projectStatus: ProjectStatus = {
  "productName": "TriggerHub 2.0",
  "statusLabel": "Active Development",
  "statusDescription": "The repository contains a working desktop foundation, core automation modules, service adapters, plugin scaffolding, and automated tests. Full end-to-end runtime wiring is still in progress.",
  "updatedAt": "2026-03-10",
  "availableNow": [
    "Electron desktop shell and Windows installer packaging are configured in the root project.",
    "Core trigger and macro modules are implemented under src/core.",
    "OBS, Spotify, and clip service modules are implemented under src/services.",
    "Plugin registry and an example plugin are implemented under src/plugins.",
    "Automated test suite passes with 79 tests across 10 files via npm run test (2026-03-10)."
  ],
  "inProgress": [
    "UI-to-runtime integration is not fully complete yet and still being wired to the runtime facade.",
    "Project documentation still contains mixed historical and current-state sections."
  ],
  "planned": [
    "Plugin manager, plugin installation flow, and SDK expansion (roadmap phase 3).",
    "Content tooling such as clip generation and export enhancements (roadmap phase 4).",
    "Community and marketplace capabilities (roadmap phase 5).",
    "AI-assisted automation and creator workflows (roadmap phase 6)."
  ],
  "proofPoints": [
    "Root scripts include desktop build and release commands: package.json",
    "Windows release artifacts and guidance are documented: docs/WINDOWS_DESKTOP_RELEASE.md",
    "Core modules exist: src/core/trigger-engine and src/core/macro-system",
    "Service adapters exist: src/services/obs-service, src/services/spotify-service, src/services/clip-service",
    "Plugin system exists: src/plugins/pluginRegistry.ts and src/plugins/example-plugin",
    "Automated tests exist and pass: src/tests/*.test.ts plus npm run test output on 2026-03-10",
    "Known gap documented in executive summary: docs/triggerhub_exec_summary.txt (point 7)"
  ],
  "limitations": [
    "Current desktop packaging target is Windows x64 (NSIS) as configured in root package.json.",
    "Some integration layers are implemented as adapter scaffolds and still need deeper production hardening.",
    "Website status is currently generated from a curated status file; CI auto-sync is not enabled yet."
  ],
  "featureSections": [
    {
      "title": "Core Architecture",
      "description": "Repository modules that are already present and test-covered.",
      "items": [
        "Trigger engine and execution graph",
        "Macro system and runner",
        "App control modules (window/hotkey/controller)",
        "Event bus infrastructure"
      ]
    },
    {
      "title": "Integrations and Extensibility",
      "description": "Adapter and extension layers available in the codebase.",
      "items": [
        "OBS service adapter",
        "Spotify service adapter",
        "Clip processing/export modules",
        "Plugin registry with example plugin"
      ]
    },
    {
      "title": "Quality and Delivery",
      "description": "Evidence that the project has an executable quality and release baseline.",
      "items": [
        "Vitest suite with 79 passing tests",
        "TypeScript + Vite build chain at root",
        "Electron desktop release workflow",
        "Documented Windows release process"
      ]
    }
  ]
} as const;
